// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cmcc_theme_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CMCCThemeConfig _$CMCCThemeConfigFromJson(Map<String, dynamic> json) {
  return CMCCThemeConfig(
    authBGImgPath: json['authBGImgPath'] as String,
    presentType: json['presentType'] as int,
    statusBarColor: json['statusBarColor'] as int,
    navColor: json['navColor'] as int,
    barStyle: json['barStyle'] as int,
    statusBarStyle: json['statusBarStyle'] as int,
    navText: json['navText'] as String,
    navTextColor: json['navTextColor'] as int,
    navTextSize: json['navTextSize'] as int,
    navReturnImgPath: json['navReturnImgPath'] as String,
    navReturnImgSize: json['navReturnImgSize'] as int,
    authNavTransparent: json['authNavTransparent'] as bool,
    navCustomBtnHidden: json['navCustomBtnHidden'] as bool,
    navCustomBtnText: json['navCustomBtnText'] as String,
    navCustomBtnTextColor: json['navCustomBtnTextColor'] as int,
    navCustomBtnTextSize: json['navCustomBtnTextSize'] as int,
    logoImgPath: json['logoImgPath'] as String,
    logoWidth: json['logoWidth'] as int,
    logoHeight: json['logoHeight'] as int,
    logoOffsetY: json['logoOffsetY'] as int,
    logoHidden: json['logoHidden'] as bool,
    logBtnText: json['logBtnText'] as String,
    logBtnTextColor: json['logBtnTextColor'] as int,
    logBtnImgPath: json['logBtnImgPath'] as String,
    logBtnOffsetY: json['logBtnOffsetY'] as int,
    logBtnOriginX: json['logBtnOriginX'] as int,
    logBtnHeight: json['logBtnHeight'] as int,
    logBtnSize: json['logBtnSize'] as int,
    numberColor: json['numberColor'] as int,
    numberSize: json['numberSize'] as int,
    numberOffsetY: json['numberOffsetY'] as int,
    numberOffsetX: json['numberOffsetX'] as int,
    switchAccHidden: json['switchAccHidden'] as bool,
    switchAccText: json['switchAccText'] as String,
    switchAccTextColor: json['switchAccTextColor'] as int,
    switchAccTextSize: json['switchAccTextSize'] as int,
    switchOffsetY: json['switchOffsetY'] as int,
    uncheckedImgPath: json['uncheckedImgPath'] as String,
    checkedImgPath: json['checkedImgPath'] as String,
    checkboxWH: json['checkboxWH'] as int,
    appPrivacyOriginX: json['appPrivacyOriginX'] as int,
    clauseOneName: json['clauseOneName'] as String,
    clauseOneUrl: json['clauseOneUrl'] as String,
    clauseTwoName: json['clauseTwoName'] as String,
    clauseTwoUrl: json['clauseTwoUrl'] as String,
    appPrivacyAlignment: json['appPrivacyAlignment'] as int,
    appPrivacyAgreeColor: json['appPrivacyAgreeColor'] as int,
    appPrivacyTextColor: json['appPrivacyTextColor'] as int,
    appPrivacyTextSize: json['appPrivacyTextSize'] as int,
    privacyOffsetY: json['privacyOffsetY'] as int,
    privacyState: json['privacyState'] as bool,
    privacySymbol: json['privacySymbol'] as bool,
    sloganText: json['sloganText'] as String,
    sloganTextSize: json['sloganTextSize'] as int,
    sloganTextColor: json['sloganTextColor'] as int,
    sloganOffsetY: json['sloganOffsetY'] as int,
    customBodyBtnText: json['customBodyBtnText'] as String,
    customBodyBtnTextColor: json['customBodyBtnTextColor'] as int,
    customBodyBtnTextSize: json['customBodyBtnTextSize'] as int,
    customBodyBtnHidden: json['customBodyBtnHidden'] as bool,
    customBodyBtnOffsetY: json['customBodyBtnOffsetY'] as int,
  );
}

Map<String, dynamic> _$CMCCThemeConfigToJson(CMCCThemeConfig instance) =>
    <String, dynamic>{
      'authBGImgPath': instance.authBGImgPath,
      'presentType': instance.presentType,
      'barStyle': instance.barStyle,
      'statusBarStyle': instance.statusBarStyle,
      'statusBarColor': instance.statusBarColor,
      'navColor': instance.navColor,
      'navText': instance.navText,
      'navTextColor': instance.navTextColor,
      'navTextSize': instance.navTextSize,
      'navReturnImgPath': instance.navReturnImgPath,
      'navReturnImgSize': instance.navReturnImgSize,
      'authNavTransparent': instance.authNavTransparent,
      'navCustomBtnHidden': instance.navCustomBtnHidden,
      'navCustomBtnText': instance.navCustomBtnText,
      'navCustomBtnTextColor': instance.navCustomBtnTextColor,
      'navCustomBtnTextSize': instance.navCustomBtnTextSize,
      'logoImgPath': instance.logoImgPath,
      'logoWidth': instance.logoWidth,
      'logoHeight': instance.logoHeight,
      'logoOffsetY': instance.logoOffsetY,
      'logoHidden': instance.logoHidden,
      'logBtnText': instance.logBtnText,
      'logBtnTextColor': instance.logBtnTextColor,
      'logBtnImgPath': instance.logBtnImgPath,
      'logBtnOffsetY': instance.logBtnOffsetY,
      'logBtnOriginX': instance.logBtnOriginX,
      'logBtnHeight': instance.logBtnHeight,
      'logBtnSize': instance.logBtnSize,
      'numberColor': instance.numberColor,
      'numberSize': instance.numberSize,
      'numberOffsetY': instance.numberOffsetY,
      'numberOffsetX': instance.numberOffsetX,
      'switchAccHidden': instance.switchAccHidden,
      'switchAccText': instance.switchAccText,
      'switchAccTextColor': instance.switchAccTextColor,
      'switchAccTextSize': instance.switchAccTextSize,
      'switchOffsetY': instance.switchOffsetY,
      'uncheckedImgPath': instance.uncheckedImgPath,
      'checkedImgPath': instance.checkedImgPath,
      'checkboxWH': instance.checkboxWH,
      'appPrivacyOriginX': instance.appPrivacyOriginX,
      'clauseOneName': instance.clauseOneName,
      'clauseOneUrl': instance.clauseOneUrl,
      'clauseTwoName': instance.clauseTwoName,
      'clauseTwoUrl': instance.clauseTwoUrl,
      'appPrivacyAlignment': instance.appPrivacyAlignment,
      'appPrivacyAgreeColor': instance.appPrivacyAgreeColor,
      'appPrivacyTextColor': instance.appPrivacyTextColor,
      'appPrivacyTextSize': instance.appPrivacyTextSize,
      'privacyOffsetY': instance.privacyOffsetY,
      'privacyState': instance.privacyState,
      'privacySymbol': instance.privacySymbol,
      'sloganText': instance.sloganText,
      'sloganTextSize': instance.sloganTextSize,
      'sloganTextColor': instance.sloganTextColor,
      'sloganOffsetY': instance.sloganOffsetY,
      'customBodyBtnText': instance.customBodyBtnText,
      'customBodyBtnTextColor': instance.customBodyBtnTextColor,
      'customBodyBtnTextSize': instance.customBodyBtnTextSize,
      'customBodyBtnHidden': instance.customBodyBtnHidden,
      'customBodyBtnOffsetY': instance.customBodyBtnOffsetY,
    };
