// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ctcc_theme_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CTCCThemeConfig _$CTCCThemeConfigFromJson(Map<String, dynamic> json) {
  return CTCCThemeConfig(
    navColor: json['navColor'] as int,
    barStyle: json['barStyle'] as int,
    navLineColor: json['navLineColor'] as int,
    navText: json['navText'] as String,
    navTextSize: json['navTextSize'] as int,
    navTextColor: json['navTextColor'] as int,
    navGoBackImg_normal: json['navGoBackImg_normal'] as String,
    navGoBackImg_highlighted: json['navGoBackImg_highlighted'] as String,
    logoImg: json['logoImg'] as String,
    logoOffsetY: json['logoOffsetY'] as int,
    logoHidden: json['logoHidden'] as bool,
    logoWidth: json['logoWidth'] as int,
    logoHeight: json['logoHeight'] as int,
    numberColor: json['numberColor'] as int,
    numberTextSize: json['numberTextSize'] as int,
    numFieldOffsetY: json['numFieldOffsetY'] as int,
    brandLabelOffsetY: json['brandLabelOffsetY'] as int,
    brandLabelTextColor: json['brandLabelTextColor'] as int,
    brandLabelTextSize: json['brandLabelTextSize'] as int,
    logBtnText: json['logBtnText'] as String,
    logBtnOffsetY: json['logBtnOffsetY'] as int,
    logBtnTextColor: json['logBtnTextColor'] as int,
    logBtnWidth: json['logBtnWidth'] as int,
    logBtnHeight: json['logBtnHeight'] as int,
    logBtnTextSize: json['logBtnTextSize'] as int,
    logBtnBackground: json['logBtnBackground'] as int,
    logBtnCornerRadius: json['logBtnCornerRadius'] as int,
    logBtnBgColor_normal: json['logBtnBgColor_normal'] as int,
    logBtnBgColor_disable: json['logBtnBgColor_disable'] as int,
    logBtnBgColor_highlighted: json['logBtnBgColor_highlighted'] as int,
    logBtnImgPath: json['logBtnImgPath'] as String,
    loadingImg: json['loadingImg'] as String,
    otherWayLogBtnText: json['otherWayLogBtnText'] as String,
    otherWayLogBtnOffsetY: json['otherWayLogBtnOffsetY'] as int,
    otherWayLogBtnTextColor_normal:
        json['otherWayLogBtnTextColor_normal'] as int,
    otherWayLogBtnTextColor_highlighted:
        json['otherWayLogBtnTextColor_highlighted'] as int,
    otherWayLogBtnTextSize: json['otherWayLogBtnTextSize'] as int,
    otherWayLogBtnHidden: json['otherWayLogBtnHidden'] as bool,
    checkState: json['checkState'] as bool,
    checkBtnImg_unchecked: json['checkBtnImg_unchecked'] as String,
    checkBtnImg_checked: json['checkBtnImg_checked'] as String,
    clauseOneName: json['clauseOneName'] as String,
    clauseOneUrl: json['clauseOneUrl'] as String,
    clauseTwoName: json['clauseTwoName'] as String,
    clauseTwoUrl: json['clauseTwoUrl'] as String,
    appShowName: json['appShowName'] as String,
    appPrivacyAgreeColor: json['appPrivacyAgreeColor'] as int,
    appPrivacyTextColor: json['appPrivacyTextColor'] as int,
    appPrivacyTextSize: json['appPrivacyTextSize'] as int,
    privacyOffsetY: json['privacyOffsetY'] as int,
  );
}

Map<String, dynamic> _$CTCCThemeConfigToJson(CTCCThemeConfig instance) =>
    <String, dynamic>{
      'navColor': instance.navColor,
      'barStyle': instance.barStyle,
      'navLineColor': instance.navLineColor,
      'navText': instance.navText,
      'navTextSize': instance.navTextSize,
      'navTextColor': instance.navTextColor,
      'navGoBackImg_normal': instance.navGoBackImg_normal,
      'navGoBackImg_highlighted': instance.navGoBackImg_highlighted,
      'logoImg': instance.logoImg,
      'logoOffsetY': instance.logoOffsetY,
      'logoHidden': instance.logoHidden,
      'logoWidth': instance.logoWidth,
      'logoHeight': instance.logoHeight,
      'numberColor': instance.numberColor,
      'numberTextSize': instance.numberTextSize,
      'numFieldOffsetY': instance.numFieldOffsetY,
      'brandLabelOffsetY': instance.brandLabelOffsetY,
      'brandLabelTextColor': instance.brandLabelTextColor,
      'brandLabelTextSize': instance.brandLabelTextSize,
      'logBtnText': instance.logBtnText,
      'logBtnOffsetY': instance.logBtnOffsetY,
      'logBtnTextColor': instance.logBtnTextColor,
      'logBtnWidth': instance.logBtnWidth,
      'logBtnHeight': instance.logBtnHeight,
      'logBtnTextSize': instance.logBtnTextSize,
      'logBtnBackground': instance.logBtnBackground,
      'logBtnCornerRadius': instance.logBtnCornerRadius,
      'logBtnBgColor_normal': instance.logBtnBgColor_normal,
      'logBtnBgColor_disable': instance.logBtnBgColor_disable,
      'logBtnBgColor_highlighted': instance.logBtnBgColor_highlighted,
      'logBtnImgPath': instance.logBtnImgPath,
      'loadingImg': instance.loadingImg,
      'otherWayLogBtnText': instance.otherWayLogBtnText,
      'otherWayLogBtnOffsetY': instance.otherWayLogBtnOffsetY,
      'otherWayLogBtnTextColor_normal': instance.otherWayLogBtnTextColor_normal,
      'otherWayLogBtnTextColor_highlighted':
          instance.otherWayLogBtnTextColor_highlighted,
      'otherWayLogBtnTextSize': instance.otherWayLogBtnTextSize,
      'otherWayLogBtnHidden': instance.otherWayLogBtnHidden,
      'checkState': instance.checkState,
      'checkBtnImg_unchecked': instance.checkBtnImg_unchecked,
      'checkBtnImg_checked': instance.checkBtnImg_checked,
      'clauseOneName': instance.clauseOneName,
      'clauseOneUrl': instance.clauseOneUrl,
      'clauseTwoName': instance.clauseTwoName,
      'clauseTwoUrl': instance.clauseTwoUrl,
      'appShowName': instance.appShowName,
      'appPrivacyAgreeColor': instance.appPrivacyAgreeColor,
      'appPrivacyTextColor': instance.appPrivacyTextColor,
      'appPrivacyTextSize': instance.appPrivacyTextSize,
      'privacyOffsetY': instance.privacyOffsetY,
    };
